# Generated by Django 6.0.4 on 2026-04-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_address_user_age_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
